In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import glob

In [ ]:
categories = ['business','entertainment','politics','sport','tech']

In [ ]:
paths = ['./du lieu cung cap/bbc/business/*.txt','./du lieu cung cap/bbc/entertainment/*.txt',
         './du lieu cung cap/bbc/politics/*.txt','./du lieu cung cap/bbc/sport/*.txt',
         './du lieu cung cap/bbc/tech/*.txt']

In [ ]:
allFiles = []
for path in paths:
    files = glob.glob(path)
    allFiles.append(files)

In [ ]:
len(allFiles)

5

In [ ]:
allFiles[0][:5]

['./du lieu cung cap/bbc/business\\255.txt',
 './du lieu cung cap/bbc/business\\256.txt',
 './du lieu cung cap/bbc/business\\257.txt',
 './du lieu cung cap/bbc/business\\258.txt',
 './du lieu cung cap/bbc/business\\259.txt']

In [ ]:
df_list = []
for i in range(5):
    text_list = []
    for file_ in allFiles[i]:
        f = open(file_,'r')
        content = f.read()
        text_list.append(content)
    df = pd.DataFrame(np.array(text_list), index=None)
    df['class'] = categories[i]
    df_list.append(df)

In [ ]:
len(df_list)

5

In [ ]:
df5 = pd.concat(df_list, ignore_index=True)
df5.head()

0     class
0  Call to overhaul UK state pension\n\nThe UK pe...  business
1  Singapore growth at 8.1% in 2004\n\nSingapore'...  business
2  Turkey knocks six zeros off lira\n\nTurkey is ...  business
3  S Korea spending boost to economy\n\nSouth Kor...  business
4  Latin America sees strong growth\n\nLatin Amer...  business

In [ ]:
df5 = df5.rename(columns={0:'content'})
df5.head()

content     class
0  Call to overhaul UK state pension\n\nThe UK pe...  business
1  Singapore growth at 8.1% in 2004\n\nSingapore'...  business
2  Turkey knocks six zeros off lira\n\nTurkey is ...  business
3  S Korea spending boost to economy\n\nSouth Kor...  business
4  Latin America sees strong growth\n\nLatin Amer...  business

In [ ]:
df5.tail()

content class
2220  BT program to beat dialler scams\n\nBT is intr...  tech
2221  Spam e-mails tempt net shoppers\n\nComputer us...  tech
2222  Be careful how you code\n\nA new European dire...  tech
2223  US cyber security chief resigns\n\nThe man mak...  tech
2224  Losing yourself in online gaming\n\nOnline rol...  tech

In [ ]:
df5.groupby('class').content.count()

class
business         510
entertainment    386
politics         417
sport            511
tech             401
Name: content, dtype: int64

In [ ]:
target = df5['class']
type(target)

pandas.core.series.Series

In [ ]:
for i in range(5):
    target = target.replace(categories[i], i)

In [ ]:
target.head()

0    0
1    0
2    0
3    0
4    0
Name: class, dtype: int64

In [ ]:
target.tail()

2220    4
2221    4
2222    4
2223    4
2224    4
Name: class, dtype: int64

In [ ]:
temp = pd.DataFrame(target)

In [ ]:
temp.head()

class
0      0
1      0
2      0
3      0
4      0

In [ ]:
source = df5['content']

In [ ]:
text_data = np.array(source)
text_data

array(['Call to overhaul UK state pension\n\nThe UK pension system has been branded inadequate and too complex by a leading retirement think-tank.\n\nThe Pensions Policy Institute (PPI) said replacing the state pension with a "citizen\'s pension" would help tackle inequality and complexity. The change would see pensions being calculated on length of residency in the UK rather than National Insurance (NI) contributions. Reform could reduce poverty by aiding people with broken employment records.\n\nThe PPI added that once the state system was reformed the government should look at options to overhaul private and workplace pensions. The think tank\'s proposals were made in response to the recent publication of the Pensions Commission\'s initial report into UK retirement savings. According to the Pensions Commission\'s report 12 million working people are not saving enough for their retirement. As a result, living standards could fall for the next generation of UK pensioners. The report a

In [ ]:
target_data = np.array(target)
target_data

array([0, 0, 0, ..., 4, 4, 4], dtype=int64)

### CountVectorizer

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
count = CountVectorizer()
count.fit(text_data)
bag_of_words = count.transform(text_data)
bag_of_words

<2225x29421 sparse matrix of type '<class 'numpy.int64'>'
	with 449254 stored elements in Compressed Sparse Row format>

In [ ]:
X = bag_of_words.toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
X.shape

(2225, 29421)

In [ ]:
y = np.array(target)

In [ ]:
y.shape

(2225,)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [ ]:
clf = MultinomialNB()
model = clf.fit(X_train,y_train)

In [ ]:
y_pred = clf.predict(X_test)

In [ ]:
print('Train score is: ', model.score(X_train,y_train))
print('Test score is: ', model.score(X_test,y_test))

Train score is:  0.9943820224719101
Test score is:  0.9662921348314607


In [ ]:
print("The accuracy score is: ", accuracy_score(y_test,y_pred)*100,'%')

The accuracy score is:  96.62921348314607 %


#### Remark: 
* Both training and testing set had high score.
* The accuracy score is high.

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score, roc_curve

In [ ]:
confusion_matrix(y_test,y_pred, labels=[0,1])

array([[107,   0],
       [  1,  69]], dtype=int64)

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.93      0.95       115
           1       0.99      0.96      0.97        72
           2       0.94      0.97      0.95        76
           3       1.00      0.99      1.00       102
           4       0.93      0.99      0.96        80

    accuracy                           0.97       445
   macro avg       0.96      0.97      0.97       445
weighted avg       0.97      0.97      0.97       445



##### Remark: 
High precision, high recall

In [ ]:
y_prob = model.predict_proba(X_test)
y_prob

array([[1.00000000e+000, 3.62410323e-200, 3.28323151e-057,
        5.10066781e-275, 1.67287400e-173],
       [1.00000000e+000, 9.92698420e-137, 2.85241939e-088,
        5.55728220e-161, 1.16597594e-101],
       [4.01096068e-175, 1.28255097e-150, 1.90864349e-169,
        1.00000000e+000, 1.51699331e-185],
       ...,
       [2.50690487e-055, 1.26240917e-081, 1.00000000e+000,
        3.70831737e-090, 1.22468590e-085],
       [1.88681073e-085, 1.00000000e+000, 2.64200503e-106,
        2.90904742e-117, 3.75178593e-065],
       [1.00000000e+000, 3.55479532e-128, 7.05844624e-066,
        1.16878608e-105, 6.96277097e-115]])

## Clustering

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
kmeans = KMeans(n_clusters=5)
kmeans.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=5, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [ ]:
centroids = kmeans.cluster_centers_
centroids

array([[ 6.08519270e-03,  5.27383367e-01,  2.02839757e-03, ...,
         2.87313576e-18,  2.02839757e-03,  5.74627151e-18],
       [ 1.28369705e-03,  3.72272144e-01,  2.98155597e-18, ...,
         2.98155597e-18,  1.19262239e-17,  5.96311195e-18],
       [ 1.42857143e-01,  1.14285714e+00, -5.42101086e-20, ...,
        -5.42101086e-20, -2.16840434e-19, -1.08420217e-19],
       [-7.37257477e-18,  2.43113772e-01,  3.03576608e-18, ...,
         1.19760479e-03,  3.59281437e-03,  2.39520958e-03],
       [ 9.00900901e-03,  3.87387387e-01,  1.24683250e-18, ...,
         1.24683250e-18,  4.98732999e-18,  2.49366500e-18]])

In [ ]:
labels = kmeans.labels_
labels

array([3, 3, 0, ..., 4, 1, 2])

In [ ]:
X = pd.DataFrame(X)

In [ ]:
X['Group'] = pd.Series(labels)
X.head()

0  1  2  3  4  5  6  7  8  9  ...  29412  29413  29414  29415  29416  \
0  0  0  0  0  0  0  0  0  0  0  ...      0      0      0      0      0   
1  0  0  0  0  0  0  0  0  0  0  ...      0      0      0      0      0   
2  0  0  0  0  0  0  0  0  0  0  ...      0      0      0      0      0   
3  0  1  0  0  0  0  0  0  0  0  ...      0      0      0      0      0   
4  0  0  0  0  0  0  0  0  0  0  ...      0      0      0      0      0   

   29417  29418  29419  29420  Group  
0      0      0      0      0      3  
1      0      0      0      0      3  
2      0      0      0      0      0  
3      0      0      0      0      0  
4      0      0      0      0      3  

[5 rows x 29422 columns]

In [ ]:
X.groupby('Group')[0].count()

Group
0    493
1    779
2      7
3    835
4    111
Name: 0, dtype: int64

## WordCloud

In [ ]:
from wordcloud import WordCloud, STOPWORDS

In [ ]:
stopwords = set(STOPWORDS)

In [ ]:
wc = WordCloud(background_color='white',max_words=2000,stopwords=stopwords)

Thưa cô, thời gian, điều kiện và khả năng không cho phép nên em chỉ có thể dừng bài này nộp cô ở đây thôi ạ. 

Em xin lỗi cô và Em sẽ cố gắng hoàn thành bài sau này ạ.

Em cảm ơn cô!