In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
digits = pd.read_csv("./du lieu cung cap/penbased-5an-nn.csv",header=None)
digits.head()

0   1   2    3   4    5    6    7    8   9   10  11  12  13   14   15  16
0   0  57  31   68  72   90  100  100   76  75  50  51  28  25   16    0   1
1  99  80  63  100  25   76   79   68  100  62  97  23  54   0    0   16   9
2   0  73  19   99  72  100   70   73   32  48   5  18  46   0  100   72   2
3  12  77  20   62  78   40   50    0    1  17   0  64  23  98  100  100   5
4   0  98  36   42  80   85   68   42   56   0  25  23  50  37  100   32   7

In [ ]:
digits.shape

(10992, 17)

In [ ]:
digits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10992 entries, 0 to 10991
Data columns (total 17 columns):
0     10992 non-null int64
1     10992 non-null int64
2     10992 non-null int64
3     10992 non-null int64
4     10992 non-null int64
5     10992 non-null int64
6     10992 non-null int64
7     10992 non-null int64
8     10992 non-null int64
9     10992 non-null int64
10    10992 non-null int64
11    10992 non-null int64
12    10992 non-null int64
13    10992 non-null int64
14    10992 non-null int64
15    10992 non-null int64
16    10992 non-null int64
dtypes: int64(17)
memory usage: 1.4 MB


The dataset has large dimensions and large number of samples. 

--> SVM algorithm will be chosen to predict the class of each sample, since it is good for multiple dimensional dataset.

In [ ]:
digits[16].unique()

array([1, 9, 2, 5, 7, 0, 3, 6, 8, 4], dtype=int64)

In [ ]:
target = digits.iloc[:,16]
data = digits.iloc[:,:16]

In [ ]:
data.head()

0   1   2    3   4    5    6    7    8   9   10  11  12  13   14   15
0   0  57  31   68  72   90  100  100   76  75  50  51  28  25   16    0
1  99  80  63  100  25   76   79   68  100  62  97  23  54   0    0   16
2   0  73  19   99  72  100   70   73   32  48   5  18  46   0  100   72
3  12  77  20   62  78   40   50    0    1  17   0  64  23  98  100  100
4   0  98  36   42  80   85   68   42   56   0  25  23  50  37  100   32

In [ ]:
target.head()

0    1
1    9
2    2
3    5
4    7
Name: 16, dtype: int64

# Splitting and applying model

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=2)

In [ ]:
clf = svm.SVC(C=100,gamma=0.001, kernel='rbf')

In [ ]:
from datetime import datetime, timedelta

In [ ]:
start_time = datetime.now()

In [ ]:
clf.fit(X_train,y_train)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
end_time = datetime.now()

In [ ]:
dt = end_time - start_time
seconds_1 = (dt.days*24*60*60 + dt.seconds)
print(seconds_1)

6


In [ ]:
y_pred = clf.predict(X_test)
y_pred

array([0, 4, 8, ..., 1, 1, 0], dtype=int64)

In [ ]:
print("Accuracy score is: ", accuracy_score(y_test,y_pred)*100,'%')

Accuracy score is:  89.31332423829014 %


In [ ]:
print("The train score is: ", clf.score(X_train,y_train)*100,'%')
print("The test score is: ", clf.score(X_test,y_test)*100,'%')

The train score is:  100.0 %
The test score is:  89.31332423829014 %


The model fit to 89% of the dataset. --> The model fits well. 

The train score is 10% higher than the test score --> It would be better if we could bring the two score closer while remaining the high accuracy.

In [ ]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[204   0   0   0   0   0   0   0  27   0]
 [  0 203   5   1   0   0   0   0  24   0]
 [  0   4 204   1   0   0   0   0  19   0]
 [  0   1   0 176   0   1   0   0  19   2]
 [  0   0   0   0 208   0   1   1  33   1]
 [  0   0   0   1   0 186   0   0  28   3]
 [  1   0   0   0   0   0 179   0   8   0]
 [  0   2   0   0   0   0   0 202  17   1]
 [  0   0   0   0   0   0   0   1 209   0]
 [  0   1   0   0   0   2   0   0  30 193]]
              precision    recall  f1-score   support

           0       1.00      0.88      0.94       231
           1       0.96      0.87      0.91       233
           2       0.98      0.89      0.93       228
           3       0.98      0.88      0.93       199
           4       1.00      0.85      0.92       244
           5       0.98      0.85      0.91       218
           6       0.99      0.95      0.97       188
           7       0.99      0.91      0.95       222
           8       0.50      1.00      0.67       210
           9       0.96     

Class 8 has the lowest precision among 10 classes. Most of them was classified into other classes.

In [ ]:
target.value_counts()

4    1144
2    1144
1    1143
0    1143
7    1142
6    1056
5    1055
3    1055
9    1055
8    1055
Name: 16, dtype: int64

The dataset is balanced between samples.

# PCA

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components=7)

In [ ]:
pca.fit(data)

PCA(copy=True, iterated_power='auto', n_components=7, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
data_trans = pca.transform(data)

In [ ]:
data_trans.shape

(10992, 7)

In [ ]:
data.shape

(10992, 16)

In [ ]:
data_new = pd.DataFrame(data_trans, columns=['Principal Component 1', 'Principal Component 2',
                                             'Principal Component 3','Principal Component 4',
                                             'Principal Component 5','Principal Component 6','Principal Component 7'])

In [ ]:
data_new.head()

Principal Component 1  Principal Component 2  Principal Component 3  \
0             -76.365162               5.246968              76.814030   
1             -68.082254              71.505068             -28.279996   
2             -14.118692             -96.755035              35.731322   
3             120.679113             -81.106924              42.128710   
4              11.096162             -72.493756              35.720567   

   Principal Component 4  Principal Component 5  Principal Component 6  \
0              18.985731               8.796097              23.096743   
1               2.857088              51.930525              -3.645254   
2              -7.417488               5.323650               1.937652   
3              35.107319              -2.641160              24.066882   
4              -4.667418              -7.727844             -20.525828   

   Principal Component 7  
0             -18.298098  
1              22.389405  
2              20.686802  
3             -10.477495  
4               1.392926

In [ ]:
X_train_n, X_test_n, y_train_n, y_test_n = train_test_split(data_new, target, test_size=0.2, random_state=2)

In [ ]:
clf_n = svm.SVC(C=100, gamma=0.001, kernel='rbf')

In [ ]:
clf_n.fit(X_train_n,y_train_n)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred_n = clf_n.predict(X_test_n)

In [ ]:
print("The accuracy score is: ", accuracy_score(y_test_n,y_pred_n)*100,'%')

The accuracy score is:  91.04138244656662 %


In [ ]:
print("The training score is: ", clf_n.score(X_train_n,y_train_n)*100,'%')
print("The testing score is: ", clf_n.score(X_test_n,y_test_n)*100,'%')

The training score is:  99.96588195155238 %
The testing score is:  91.04138244656662 %


In [ ]:
print(confusion_matrix(y_test_n,y_pred_n))
print(classification_report(y_test_n,y_pred_n))

[[219   0   0   0   1   0   3   0   8   0]
 [  0 194  21   2   0   1   0   9   3   3]
 [  0  28 193   3   0   0   0   3   1   0]
 [  0   4   2 178   1   6   0   2   3   3]
 [  0   2   0   3 224   0   4   1   3   7]
 [  0   0   0   1   2 200   1   0   7   7]
 [  1   0   1   0   1   0 184   0   1   0]
 [  0   8   2   0   2   0   0 205   3   2]
 [  1   0   1   0   0   1   0   4 201   2]
 [  0   3   0   7   2   6   0   1   3 204]]
              precision    recall  f1-score   support

           0       0.99      0.95      0.97       231
           1       0.81      0.83      0.82       233
           2       0.88      0.85      0.86       228
           3       0.92      0.89      0.91       199
           4       0.96      0.92      0.94       244
           5       0.93      0.92      0.93       218
           6       0.96      0.98      0.97       188
           7       0.91      0.92      0.92       222
           8       0.86      0.96      0.91       210
           9       0.89     

In [ ]:
pca1 = PCA(n_components=8)

In [ ]:
pca1.fit(data)

PCA(copy=True, iterated_power='auto', n_components=8, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [ ]:
data_trans1 = pca1.transform(data)

In [ ]:
data_trans1.shape

(10992, 8)

In [ ]:
data.shape

(10992, 16)

In [ ]:
data_new1 = pd.DataFrame(data_trans1, columns=['Principal Component 1', 'Principal Component 2',
                                             'Principal Component 3','Principal Component 4',
                                             'Principal Component 5','Principal Component 6',
                                               'Principal Component 7','Principal Component 8'])

In [ ]:
data_new1.head()

Principal Component 1  Principal Component 2  Principal Component 3  \
0             -76.365162               5.246968              76.814030   
1             -68.082254              71.505068             -28.279996   
2             -14.118692             -96.755035              35.731322   
3             120.679113             -81.106924              42.128710   
4              11.096162             -72.493756              35.720567   

   Principal Component 4  Principal Component 5  Principal Component 6  \
0              18.985731               8.796097              23.096743   
1               2.857088              51.930525              -3.645254   
2              -7.417488               5.323650               1.937652   
3              35.107319              -2.641160              24.066882   
4              -4.667418              -7.727844             -20.525828   

   Principal Component 7  Principal Component 8  
0             -18.298098             -18.672940  
1              22.389405              -1.883601  
2              20.686802             -34.892333  
3             -10.477495               5.214637  
4               1.392926               9.019466

In [ ]:
X_train_n1, X_test_n1, y_train_n1, y_test_n1 = train_test_split(data_new1, target, test_size=0.2, random_state=2)

In [ ]:
clf_n1 = svm.SVC(C=100, gamma=0.001, kernel='rbf')

In [ ]:
s_time = datetime.now()

In [ ]:
clf_n1.fit(X_train_n1,y_train_n1)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
e_time = datetime.now()

In [ ]:
dt2 = e_time - s_time
seconds_2 = (dt2.days*24*60*60 + dt2.seconds)
print(seconds_2)

2


In [ ]:
y_pred_n1 = clf_n1.predict(X_test_n1)

In [ ]:
print("The accuracy score is: ", accuracy_score(y_test_n1,y_pred_n1)*100,'%')

The accuracy score is:  92.54206457480673 %


In [ ]:
print("The training score is: ", clf_n1.score(X_train_n1,y_train_n1)*100,'%')
print("The testing score is: ", clf_n1.score(X_test_n1,y_test_n1)*100,'%')

The training score is:  100.0 %
The testing score is:  92.54206457480673 %


In [ ]:
print(confusion_matrix(y_test_n1,y_pred_n1))
print(classification_report(y_test_n1,y_pred_n1))

[[218   0   0   0   1   0   2   0  10   0]
 [  0 203  15   3   0   1   0   3   5   3]
 [  0  18 202   2   0   0   0   1   5   0]
 [  0   5   1 183   0   2   0   2   4   2]
 [  0   0   0   2 228   0   3   1   6   4]
 [  0   0   0   2   0 202   1   0   8   5]
 [  1   0   1   0   0   0 185   0   1   0]
 [  0   5   2   0   3   0   0 204   7   1]
 [  1   0   0   0   0   1   0   2 204   2]
 [  0   4   0   4   1   6   0   0   5 206]]
              precision    recall  f1-score   support

           0       0.99      0.94      0.97       231
           1       0.86      0.87      0.87       233
           2       0.91      0.89      0.90       228
           3       0.93      0.92      0.93       199
           4       0.98      0.93      0.96       244
           5       0.95      0.93      0.94       218
           6       0.97      0.98      0.98       188
           7       0.96      0.92      0.94       222
           8       0.80      0.97      0.88       210
           9       0.92     

#### Remark

After reducing dimensions from 16 to 8 using PCA, the precision score for class 8 has increased sharply (from 50% to 80%).

Moreover, the time required to train the model is shortened (from 6s to 2s), the difference in score between train and test set is slighly smaller. Test score is higher after PCA.

Applying PCA is better for predicting classes of the dataset.